# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(max_length=40, unique=True)),
                ('landline_number', models.CharField(max_length=40, unique=True)),
                ('open_time', models.CharField(max_length=5)),
                ('close_time', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('treatment_center', 'Treatment Center'), ('social_hygiene_clinic', 'Social Hygiene Clinic'), ('testing_hub', 'Testing Hub')], max_length=2)),
                ('staff', models.TextField()),
                ('additional_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(max_length=40, unique=True)),
                ('landline_number', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
