# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratoruser',
            name='category',
            field=models.CharField(choices=[('treatment_center', 'Treatment Center'), ('social_hygiene_clinic', 'Social Hygiene Clinic'), ('testing_hub', 'Testing Hub')], max_length=21),
        ),
    ]
