# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171030_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratoruser',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
