# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('open_time', models.CharField(max_length=5, null=True)),
                ('close_time', models.CharField(max_length=5, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=21)),
                ('staff', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
            ],
        ),
    ]
