# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_administratordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
