# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171030_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratoruser',
            name='category',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='landline_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
