# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0003_baseuser_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorServices',
            fields=[
                ('admin_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AdministratorDetails')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service')),
            ],
        ),
        migrations.AddField(
            model_name='administratordetails',
            name='services',
            field=models.ManyToManyField(through='users.AdministratorServices', to='dashboard.Service'),
        ),
    ]
