# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171106_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorservices',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
