# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171031_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratoruser',
            name='close_time',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='administratoruser',
            name='landline_number',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='administratoruser',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administratoruser',
            name='mobile_number',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='administratoruser',
            name='open_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
