# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171101_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratoruser',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='administratoruser',
            name='staff',
            field=models.TextField(null=True),
        ),
    ]
