# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171109_1327'),
        ('users', '0006_auto_20171108_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorProducts',
            fields=[
                ('admin_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AdministratorDetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product')),
            ],
        ),
        migrations.AddField(
            model_name='administratordetails',
            name='products',
            field=models.ManyToManyField(through='users.AdministratorProducts', to='dashboard.Product'),
        ),
    ]
