# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171101_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='landline_number',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='mobile_number',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
