# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171109_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorproducts',
            name='description',
            field=models.TextField(default='now'),
            preserve_default=False,
        ),
    ]
