# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_administratorproducts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratorproducts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='administratorproducts',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='administratorproducts',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
