# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratordetails',
            name='address',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
