# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20171116_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AdministratorDetails'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Timeslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
