# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20171116_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_info',
            field=models.TextField(default='alsdkjf'),
            preserve_default=False,
        ),
    ]
